### PR TITLE
feat: Now we can group and sort anchors

### PR DESCRIPTION
**Pull request by eggachecat**
- Now we can group and sort anchors
- Anchors can have properties now
- Thus we can group anchors across workspace
- Also the autocompletion for existed epic are supported

### CODE REVIEW

**Comment by eggachecat** [comment]
image

**Comment by eggachecat** [comment]
@macjuul Hello would you like to do a code review for this? Thanks a lot!

**Comment by eggachecat** [comment]
BTW @macjuul should we configure some lint rules for this project in case many of us could have different default coding styles.

**Comment by macjuul** [comment]
Will give the PR a review in the near future, currently caught up in some busy tasks for the moment. At a quick glance it looks promising and mostly ready to be merged 👍 

Linting rules would be a great addition, however I've always struggled getting ESLint to work and end up getting rid of it all together. If you have any suggestions for it feel free to let me know or open a separate PR.

Thanks!

**Comment by eggachecat** [comment]
**UPDATE**: I am using this extension with this feature to learn the source code of react, the performance is just fine😎😎. 
And I realized that maybe putting _chapter_ into epic may be a good idea

**Comment by eggachecat** [comment]
TODO: right-click-context-menu would be a great option for sorting

**Comment by macjuul** [comment]
Heyo! Just checking in. Looks like the latest PR merge caused some conflicts. I'll take care of merging this PR once they are resolved and you're confident grouping and sorting is ready 🙂

**Comment by eggachecat** [comment]
@macjuul just make another PR to resolve the PR conflict. Would you like to do a code review?

BTW, should we make the default value of **maxFiles** larger up to something like 500? Sometimes it really is confusing when the extension misses some anchors in a large repo.

**Comment by macjuul** [comment]
I've upped the `maxFiles` limit to 250 for now and fixed some inconsistencies around it.

I did run into some issues getting ESLint to work, and I had to fix some issues for it to calm down, however it caused some conflicts on your branch, so I quickly fixed those too. 

I'll give this branch some additional testing before merging it, although it's looking good! 🙂

**Comment by macjuul** [comment]
Hey! I've tested your branch and everything seems to work great, and I really appreciate your PR!

One minor change I made was to remove the default Epic and instead opt to not display untagged anchors in the tree in order to keep epics more streamlined, as it may have been confusing to new users. Other than that everything's good to go!

**Comment by eggachecat** [comment]
@macjuul Great! Nice work!!
BTW I cannot find the latest version from vscode , would you like to publish it? 
Can not wait for sharing(showing off :-)) it with my colleagues!

**Comment by macjuul** [comment]
@eggachecat I'll release the new version shortly (hopefully today) along with some other minor changes

**Pull request merged**
