### PR TITLE
Now we can group and sort anchors

### PR DESCRIPTION
**Pull request by eggachecat**
- Now we can group and sort anchors

- Anchors can have properties now

### CODE REVIEW

**Comment by eggachecat** [comment]
Here's what it looks like

demo

**Comment by eggachecat** [comment]
I think sometimes it is super useful to have sorted and grouped anchors when we want to figure out multiple workflows (i.e. a sorted group per each single flow)...

**Comment by eggachecat** [comment]
...

**Comment by eggachecat** [comment]
@macjuul hi boss This has been one year... Let me know whether this feature is useful and if it does I would love to continue improving the code

**Comment by macjuul** [comment]
Hey man, sorry I haven't noticed your request until now

This seems like a great feature to add and can definitely help with the goal Comment Anchors is trying to achieve 😁 

Some notes I have
- We should look into renaming Epic Anchors into something more descriptive e.g. Anchor Groups
- I'm still not entirely sure on the sorting aspect of the PR, since the regular anchor view supports changing the order in which anchors are displayed already. Perhaps it's best to use that same setting for the grouped anchors, and instead dedicate the panel to just the groups
- If we do remove the `seq` tags the groups syntax could perhaps be simplified to just `ANCHOR[group1,group2]`
- Before I add new features, I'll update the extension first in order to fix the larger bugs and improve the code a bit. One thing I'm looking into changing is the regex as it's too convoluted has issues with certain characters. Once that's done you'll have to update the new regex with your group functionality

If you have any further questions just let me know as I'll be more active on here now. Thanks again for the PR!

**Comment by eggachecat** [comment]
Okay! I will check those!

**Comment by macjuul** [comment]
A quick heads-up. I've made many changes today in order to fix long standing issues with Comment Anchors. I've altered the folder structure, simplified the regex, and performed some more house keeping tasks.

You may want to update your PR to support the latest commit and see how much it has been effected by all the changes 🙂

**Comment by eggachecat** [comment]
Okay! I will have a look in this weekend I think.. Sorry for the delay. I am suffering from [996](https://en.wikipedia.org/wiki/996_working_hour_system) right now..

**Pull request closed without merging**
